ifeq (${XRAY_XC7Z}, 1)
part.yaml: design.bit
	${XRAY_TOOLS_DIR}/gen_part_base_yaml $< -i | python3 ../generate.py
else
part.yaml: design.debug.bit
	${XRAY_TOOLS_DIR}/gen_part_base_yaml $< > $@
endif

design.bit debug.perframecrc.bit design.debug.bit: ../generate.tcl
	vivado -mode batch -source ../generate.tcl

