# Copyright (C) 2017-2020  The Project X-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
MAKETODO_FLAGS=--re "^INT_[LR].FAN_ALT[0-9]\.BYP_BOUNCE.*$$"
GENERATE_FLAGS=--todo ../todo.txt
N = 48
SEGMATCH_FLAGS=-m 15 -M 45 -c 2
include ../int_loop.mk

