# Types of things
parts-fuzzers: ["fuzzers"]
parts-minitests: ["minitests"]
parts-experiments: ["experiments"]
parts-docs: ["docs", "*.md", "COPYING"]
parts-infra: [".github", ".style.yapf", "vagrant", "download-latest-db.sh"]
parts-tools: ["tools", "utils", "htmlgen"]
parts-third-party: ["third_party", ".gitmodules"]
