steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'DEV_ENV_IMAGE=${_DEV_ENV_IMAGE}'
    - '--build-arg'
    - 'NUM_PARALLEL_JOBS=${_NUM_CPUS}'
    - '--build-arg'
    - 'BUILD_TYPE=${_BUILD_TYPE}'
    - '-t'
    - '${_GCR_ZONE}/$PROJECT_ID/${_IMAGE_NAME}:${SHORT_SHA}'
    - '-f'
    - '.github/cloudbuild/Dockerfile'
    - '.'
options:
  disk_size_gb: 1000
  machine_type: N1_HIGHCPU_32
timeout: '24h0m0s'
substitutions:
  _GCR_ZONE: 'gcr.io'
  _IMAGE_NAME: 'prjxray-db'
  _NUM_CPUS: '16'
  _BUILD_TYPE: ''
images:
  - '${_GCR_ZONE}/$PROJECT_ID/${_IMAGE_NAME}:${SHORT_SHA}'
