# Copyright (C) 2017-2020  The Project X-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
N ?= 6
GENERATE_ARGS?="--oneval 1 --design params.csv --dword 0 --dframe 21"
include ../fuzzaddr/common.mk

