N ?= 2
# Was expecting oneval 3, but bits might be inverted
# FIXME: dword
# Ex: 0002009D_029_15
GENERATE_ARGS?="--oneval 0 --design params.csv --dframe 14 --dword 0 --dbit 27"
include ../fuzzaddr/common.mk
