N ?= 6
# Was expecting oneval 3, but bits might be inverted
# FIXME: dword
# Ex: 0002009D_029_15
GENERATE_ARGS?="--oneval 2 --design params.csv --dframe 1D --dword 29 --dbit 15"
include ../fuzzaddr/common.mk
