# Copyright (C) 2017-2020  The Project X-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
N ?= 2
GENERATE_ARGS?="--oneval 0 --design params.csv --dframe 1c --dword 0 --dbit 16"
include ../fuzzaddr/common.mk
