# read/write width is relatively slow to resolve
# Even slower with multi bit masks...
N := 20
include ../fuzzer.mk

database: $(SPECIMENS_OK)

pushdb:
	echo "FIXME" && false

.PHONY: database pushdb

