# Copyright (C) 2017-2020  The Project X-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
# read/write width is relatively slow to resolve
# Even slower with multi bit masks...
N := 20
include ../fuzzer.mk

database: $(SPECIMENS_OK)

pushdb:
	echo "FIXME" && false

.PHONY: database pushdb

