# Copyright (C) 2017-2020  The Project X-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC
MAKETODO_FLAGS=--re ".*" --not-endswith ".VCC_WIRE"
GENERATE_FLAGS=--todo ../todo.txt
N = 24
SEGMATCH_FLAGS=-m 20 -M 45
include ../int_loop.mk

