N ?= 2
# Was expecting oneval 3, but bits might be inverted
# FIXME: dword
# Ex: 0002009C_077_16
GENERATE_ARGS?="--oneval 2 --design params.csv --dframe 1C --dword 77 --dbit 16"
include ../fuzzaddr/common.mk
