name: Image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  BuildAndPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE: ghcr.io/f4pga/prjxray/ci

    steps:

      - name: Build image prjxray/ci
        run: |
          docker build -t $IMAGE - <<EOF
          FROM ubuntu:bionic
          RUN apt-get update -qq \
            && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
               bash \
               bison \
               build-essential \
               ca-certificates \
               clang-format \
               cmake \
               psmisc \
               colordiff \
               coreutils \
               git \
               flex \
               python3 \
               python3-dev \
               python3-venv \
               xsltproc \
               libtinfo5 \
            && apt-get autoclean && apt-get clean && apt-get -y autoremove \
            && update-ca-certificates \
            && rm -rf /var/lib/apt/lists/*

      - uses: pyTooling/Actions/with-post-step@r0
        with:
          main: |
            echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
            docker push $IMAGE
          post: docker logout ghcr.io
